{"links": {"self": {"href": "data/repositories/osrf/subt/issues/110/comments/53129856.json"}, "html": {"href": "#!/osrf/subt/issues/110#comment-53129856"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/110.json"}}, "type": "issue", "id": 110, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "X1_SENSOR_CONFIG_4 model not publishing points again"}, "content": {"raw": "@{557058:095b1e12-74ed-4e20-b44f-2f0745b616e0} , yes I am seeing points again. Thanks.", "markup": "markdown", "html": "<p><span class=\"ap-mention\" data-atlassian-id=\"557058:095b1e12-74ed-4e20-b44f-2f0745b616e0\">@Nate Koenig</span> , yes I am seeing points again. Thanks.</p>", "type": "rendered"}, "created_on": "2019-07-24T17:46:14.806076+00:00", "user": {"display_name": "Sarah Kitchen", "uuid": "{6e33efb0-dd9b-4c54-9597-53cb73099f33}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B6e33efb0-dd9b-4c54-9597-53cb73099f33%7D"}, "html": {"href": "https://bitbucket.org/%7B6e33efb0-dd9b-4c54-9597-53cb73099f33%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/29a4e0df12f5ebcc54cd596a60606526d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSK-1.png"}}, "nickname": "snkitche", "type": "user", "account_id": "5be108d7216ccf49622e6b67"}, "updated_on": null, "type": "issue_comment", "id": 53129856}