{"links": {"self": {"href": "data/repositories/osrf/subt/issues/168/comments/53785288.json"}, "html": {"href": "#!/osrf/subt/issues/168#comment-53785288"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/168.json"}}, "type": "issue", "id": 168, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "Unable to launch multiple vehicles"}, "content": {"raw": "@{5cf75629ff02b50ea27b2817} , \n\nI tested both tutorials and here are my results.  \n\nFor [tutorial 1](#!/osrf/subt/wiki/tutorials/cloudsim), with no file when doing ls -l /tmp/.docker.xauth I get both robots to communicate and move but I get some error messages on different terminals \\( including not binding error\\). Are these expected?\n\n So here is a detailed description:\n\n**Terminal 1 \\(No Error\\):** \n\n./run.bash cloudsim\\_sim cloudsim\\_sim.ign robotName1:=X1 robotConfig1:=X1\\_SENSOR\\_CONFIG1 robotName2:=X2 robotConfig2:=X2\\_SENSOR\\_CONFIG1\n\n**Terminal 2 \\(bridge 1, tf\\_world\\_static-4 finished, death of process\\):**\n\n./run.bash cloudsim\\_bridge robotName1:=X1 robotConfig1:=X1\\_SENSOR\\_CONFIG1\n\n\u2026\n\n\\[Dbg\\] \\[[Manager.cc:421](http://Manager.cc:421)\\] Death of process\\[52\\] with name\\[x1\\_description\\].  \nprocess\\[X1/ros1\\_ign\\_bridge\\_imu-1\\]: started with pid \\[108\\]  \nprocess\\[subt\\_ros\\_relay-3\\]: started with pid \\[127\\]  \nprocess\\[X1/ros1\\_ign\\_bridge\\_pose-2\\]: started with pid \\[140\\]  \nprocess\\[tf\\_world\\_static-4\\]: started with pid \\[153\\]  \n\u2026.\n\nprocess\\[X1/pose\\_tf\\_broadcaster-9\\]: started with pid \\[249\\]  \n\\[tf\\_world\\_static-4\\] process has finished cleanly\n\n**Terminal 3 \\(bridge 2, death of process\\)**\n\n./run.bash cloudsim\\_bridge robotName2:=X2 robotConfig2:=X2\\_SENSOR\\_CONFIG1\n\n\u2026\n\n\\[Dbg\\] \\[[Manager.cc:421](http://Manager.cc:421)\\] Death of process\\[52\\] with name\\[x2\\_description\\].\n\n\u2026\n\nprocess\\[X2/ros1\\_ign\\_bridge\\_odom-7\\]: started with pid \\[182\\]  \nprocess\\[X2/ros1\\_ign\\_bridge\\_battery\\_state-8\\]: started with pid \\[194\\]  \nprocess\\[X2/pose\\_tf\\_broadcaster-9\\]: started with pid \\[206\\]\n\n**Terminal 4 and 5 show the same error \\(control 1 and 2\\)**\n\nroslaunch subt\\_example example\\_robot.launch name:=X1\n\n\u2026\n\n\\[CommsClient\\] Retrying register..  \n\\[X1\\] CommsClient::Register: Problem registering with broker  \n\\[CommsClient\\] Validation service not available, invalid address or model not available  \n\\[X1\\] Bind\\(\\) error: Trying to bind before communications are enabled!  \n\\[FATAL\\] \\[1567765907.647300154, 55.940000000\\]: subt\\_example\\_node did not successfully bind to the CommsClient  \n\\[ INFO\\] \\[1567765907.649587710, 55.944000000\\]: Starting competitor\n\n\\[ INFO\\] \\[1567765946.030639903, 93.116000000\\]: TeleopCommCallback", "markup": "markdown", "html": "<p><span class=\"ap-mention\" data-atlassian-id=\"5cf75629ff02b50ea27b2817\">@Alfredo Bencomo</span> , </p>\n<p>I tested both tutorials and here are my results.  </p>\n<p>For <a data-is-external-link=\"true\" href=\"#!/osrf/subt/wiki/tutorials/cloudsim\" rel=\"nofollow\">tutorial 1</a>, with no file when doing ls -l /tmp/.docker.xauth I get both robots to communicate and move but I get some error messages on different terminals ( including not binding error). Are these expected?</p>\n<p>So here is a detailed description:</p>\n<p><strong>Terminal 1 (No Error):</strong> </p>\n<p>./run.bash cloudsim_sim cloudsim_sim.ign robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG1 robotName2:=X2 robotConfig2:=X2_SENSOR_CONFIG1</p>\n<p><strong>Terminal 2 (bridge 1, tf_world_static-4 finished, death of process):</strong></p>\n<p>./run.bash cloudsim_bridge robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG1</p>\n<p>\u2026</p>\n<p>[Dbg] [<a data-is-external-link=\"true\" href=\"http://Manager.cc:421\" rel=\"nofollow\">Manager.cc:421</a>] Death of process[52] with name[x1_description].<br />\nprocess[X1/ros1_ign_bridge_imu-1]: started with pid [108]<br />\nprocess[subt_ros_relay-3]: started with pid [127]<br />\nprocess[X1/ros1_ign_bridge_pose-2]: started with pid [140]<br />\nprocess[tf_world_static-4]: started with pid [153]<br />\n\u2026.</p>\n<p>process[X1/pose_tf_broadcaster-9]: started with pid [249]<br />\n[tf_world_static-4] process has finished cleanly</p>\n<p><strong>Terminal 3 (bridge 2, death of process)</strong></p>\n<p>./run.bash cloudsim_bridge robotName2:=X2 robotConfig2:=X2_SENSOR_CONFIG1</p>\n<p>\u2026</p>\n<p>[Dbg] [<a data-is-external-link=\"true\" href=\"http://Manager.cc:421\" rel=\"nofollow\">Manager.cc:421</a>] Death of process[52] with name[x2_description].</p>\n<p>\u2026</p>\n<p>process[X2/ros1_ign_bridge_odom-7]: started with pid [182]<br />\nprocess[X2/ros1_ign_bridge_battery_state-8]: started with pid [194]<br />\nprocess[X2/pose_tf_broadcaster-9]: started with pid [206]</p>\n<p><strong>Terminal 4 and 5 show the same error (control 1 and 2)</strong></p>\n<p>roslaunch subt_example example_robot.launch name:=X1</p>\n<p>\u2026</p>\n<p>[CommsClient] Retrying register..<br />\n[X1] CommsClient::Register: Problem registering with broker<br />\n[CommsClient] Validation service not available, invalid address or model not available<br />\n[X1] Bind() error: Trying to bind before communications are enabled!<br />\n[FATAL] [<a href=\"#!/osrf/subt/commits/1567765907\" rel=\"nofollow\" class=\"ap-connect-link\">1567765907</a>.<a href=\"#!/osrf/subt/commits/647300154\" rel=\"nofollow\" class=\"ap-connect-link\">647300154</a>, 55.<a href=\"#!/osrf/subt/commits/940000000\" rel=\"nofollow\" class=\"ap-connect-link\">940000000</a>]: subt_example_node did not successfully bind to the CommsClient<br />\n[ INFO] [<a href=\"#!/osrf/subt/commits/1567765907\" rel=\"nofollow\" class=\"ap-connect-link\">1567765907</a>.<a href=\"#!/osrf/subt/commits/649587710\" rel=\"nofollow\" class=\"ap-connect-link\">649587710</a>, 55.<a href=\"#!/osrf/subt/commits/944000000\" rel=\"nofollow\" class=\"ap-connect-link\">944000000</a>]: Starting competitor</p>\n<p>[ INFO] [<a href=\"#!/osrf/subt/commits/1567765946\" rel=\"nofollow\" class=\"ap-connect-link\">1567765946</a>.<a href=\"#!/osrf/subt/commits/030639903\" rel=\"nofollow\" class=\"ap-connect-link\">030639903</a>, 93.<a href=\"#!/osrf/subt/commits/116000000\" rel=\"nofollow\" class=\"ap-connect-link\">116000000</a>]: TeleopCommCallback</p>", "type": "rendered"}, "created_on": "2019-09-06T11:20:39.581388+00:00", "user": {"display_name": "Hector Escobar", "uuid": "{1c140a49-f2c5-4727-abd9-eb427bfe4253}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B1c140a49-f2c5-4727-abd9-eb427bfe4253%7D"}, "html": {"href": "https://bitbucket.org/%7B1c140a49-f2c5-4727-abd9-eb427bfe4253%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/8da90eb0e9b47c9adfc2893e5190483fd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsHE-1.png"}}, "nickname": "hector_escobar", "type": "user", "account_id": "5b5b1c941394ae6a72c021df"}, "updated_on": null, "type": "issue_comment", "id": 53785288}