{"links": {"self": {"href": "data/repositories/osrf/subt/issues/363/comments/56636903.json"}, "html": {"href": "#!/osrf/subt/issues/363#comment-56636903"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/363.json"}}, "type": "issue", "id": 363, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "cv_bridge exception when using any vehicle with depth camera (RGBD)"}, "content": {"raw": "I did a bisection search through previous commits and found that the error message started printing in revision 2428 when the bridge\\_logger was introduced. I also found that the error statement can be suppressed by commenting out \\(not launching\\) the bridge\\_logger node in subt\\_ros/launch/competition\\_init.launch.", "markup": "markdown", "html": "<p>I did a bisection search through previous commits and found that the error message started printing in revision 2428 when the bridge_logger was introduced. I also found that the error statement can be suppressed by commenting out (not launching) the bridge_logger node in subt_ros/launch/competition_init.launch.</p>", "type": "rendered"}, "created_on": "2020-03-23T22:00:24.286280+00:00", "user": {"display_name": "Neil Johnson", "uuid": "{ace5bb77-1f3f-47ce-ad95-ea205b690930}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bace5bb77-1f3f-47ce-ad95-ea205b690930%7D"}, "html": {"href": "https://bitbucket.org/%7Bace5bb77-1f3f-47ce-ad95-ea205b690930%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/7ff0dae55a4eb43a021cc9c08bbf30f5d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsNJ-3.png"}}, "nickname": "realdealneil1980", "type": "user", "account_id": "557058:21a4b3d0-2fa2-4202-9385-337ffcf40b2f"}, "updated_on": "2020-03-23T22:00:42.936104+00:00", "type": "issue_comment", "id": 56636903}