{"links": {"self": {"href": "data/repositories/osrf/subt/issues/136/comments/53194424.json"}, "html": {"href": "#!/osrf/subt/issues/136#comment-53194424"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/136.json"}}, "type": "issue", "id": 136, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "X3/X4 Not Responding to Velocity Commands in Local Cloudsim"}, "content": {"raw": "Cleared all of my Docker images and rebuilding from scratch.  I'll follow up with an `rqt_graph` whenever I get it all back up and running if the issue persists.", "markup": "markdown", "html": "<p>Cleared all of my Docker images and rebuilding from scratch.  I'll follow up with an <code>rqt_graph</code> whenever I get it all back up and running if the issue persists.</p>", "type": "rendered"}, "created_on": "2019-07-29T18:42:14.683334+00:00", "user": {"display_name": "Arthur Schang", "uuid": "{1403972a-9b64-442b-a69c-d7e9557e1d87}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B1403972a-9b64-442b-a69c-d7e9557e1d87%7D"}, "html": {"href": "https://bitbucket.org/%7B1403972a-9b64-442b-a69c-d7e9557e1d87%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/initials/AS-0.png"}}, "nickname": "Arthur Schang", "type": "user", "account_id": "557058:14b7fd50-d65a-47a8-825c-fa89681d07bd"}, "updated_on": null, "type": "issue_comment", "id": 53194424}