{"links": {"self": {"href": "data/repositories/osrf/subt/issues/378/comments/56827491.json"}, "html": {"href": "#!/osrf/subt/issues/378#comment-56827491"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/378.json"}}, "type": "issue", "id": 378, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "Robots not working with new docker images"}, "content": {"raw": "Is that the correct groupd id? I looked at the logs, and I don't see errors. I also don't see the `rostopic_247_1586233084153.log` file.", "markup": "markdown", "html": "<p>Is that the correct groupd id? I looked at the logs, and I don't see errors. I also don't see the <code>rostopic_247_1586233084153.log</code> file.</p>", "type": "rendered"}, "created_on": "2020-04-07T13:50:25.558575+00:00", "user": {"display_name": "Nate Koenig", "uuid": "{c862cdd9-fcc8-4419-9fc7-e20db14b8fcb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D"}, "html": {"href": "https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:095b1e12-74ed-4e20-b44f-2f0745b616e0/ca24bb11-4787-4b14-a20d-d91835e9bde2/128"}}, "nickname": "Nathan Koenig", "type": "user", "account_id": "557058:095b1e12-74ed-4e20-b44f-2f0745b616e0"}, "updated_on": "2020-04-07T13:57:21.541250+00:00", "type": "issue_comment", "id": 56827491}