{"links": {"self": {"href": "data/repositories/osrf/subt/issues/91/comments/52912218.json"}, "html": {"href": "#!/osrf/subt/issues/91#comment-52912218"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/91.json"}}, "type": "issue", "id": 91, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "TF data from ignition does not follow REP 105"}, "content": {"raw": "@{557058:14b7fd50-d65a-47a8-825c-fa89681d07bd} , thanks I\u2019ve cloned your ignition branch and am trying to run the following:\n\nTerminal 1:\n\n```\nign launch -v 4 virtual_stix.ign robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG_4\n```\n\nTerminal 2:\n\n```\nroslaunch helloworld_subt_launch helloworld-ign.launch\n```\n\nWith errors and warnings of the following type:\n\n```\n[ WARN] [1562686798.884227893, 101.462000000]: W0709 11:39:58.000000 11804 tf_bridge.cc:52] Lookup would require extrapolation into the past.  Requested time 90.050000000 but the earliest data is at time 91.461000000, when looking up transform from frame [X1/base_link/imu_sensor] to frame [X1]\n[ WARN] [1562686798.884300216, 101.462000000]: W0709 11:39:58.000000 11804 tf_bridge.cc:52] Lookup would require extrapolation into the past.  Requested time 90.050000000 but the earliest data is at time 91.461000000, when looking up transform from frame [X1/base_link/imu_sensor] to frame [X1]\n[ERROR] [1562686799.471079435, 101.650000000]: Extrapolation Error looking up robot pose: Lookup would require extrapolation into the past.  Requested time 90.623000000 but the earliest data is at time 91.649000000, when looking up transform from frame [X1/base_link] to frame [map]\n\n[ WARN] [1562686799.512097470, 101.662000000]: W0709 11:39:59.000000 11804 tf_bridge.cc:52] Could not find a connection between 'X1' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.\n[ WARN] [1562686800.116323704, 101.863000000]: W0709 11:40:00.000000 11804 tf_bridge.cc:52] Could not find a connection between 'X1' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.\n```\n\nAre these the same kinds of complaints you guys saw \\(as indicated by your commit message\\)?\n\nI\u2019m also getting these errors from the ignition terminal:\n\n```\n[ERROR] [1562686764.351808883]: Client [/X1/move_base] wants topic /X1/points to have datatype/md5sum [sensor_msgs/PointCloud/d8e9c3f5afbdd8a130fd1d2763945fca], but our version has [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181]. Dropping connection.\n[ERROR] [1562687005.015042569]: Client [/X1/move_base] wants topic /X1/points to have datatype/md5sum [sensor_msgs/PointCloud/d8e9c3f5afbdd8a130fd1d2763945fca], but our version has [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181]. Dropping connection.\n```\n\nI\u2019m also attaching my tf trees from view\\_frames. Notably, I have base\\_link->X1->X1/base\\_link. Is this expected behavior? Is this issue related at all to Issue [#100](#!/osrf/subt/issues/100/accurate-uav-odometry-filtered-rostopic)?\n\nHere is the roswtf output:\n\n```\nLoaded plugin tf.tfwtf\nLoaded plugin openni2_launch.wtf_plugin\nNo package or stack in context\n================================================================================\nStatic checks summary:\n\nNo errors or warnings\n================================================================================\nBeginning tests of your ROS graph. These may take awhile...\nanalyzing graph...\n... done analyzing graph\nrunning graph rules...\n... done running graph rules\nrunning tf checks, this will take a second...\n... tf checks complete\n\nOnline checks summary:\n\nFound 1 warning(s).\nWarnings are things that may be just fine, but are sometimes at fault\n\nWARNING The following node subscriptions are unconnected:\n * /rviz:\n   * /X1/projected_map_updates\n   * /X1/map_updates\n * /X1/move_base:\n   * /X1/move_base/cancel\n   * /X1/scan\n   * /X1/move_base_simple/goal\n\n\nFound 2 error(s).\n\nERROR The following nodes should be connected but aren't:\n * /X1/move_base->/X1/move_base (/X1/move_base/global_costmap/footprint)\n * /ignition->/X1/move_base (/X1/points)\n * /X1/move_base->/X1/move_base (/X1/move_base/local_costmap/footprint)\n\nERROR Different number of openni2 sensors found.\n * 0 openni2 sensors found (expected: 1).\n```", "markup": "markdown", "html": "<p><span class=\"ap-mention\" data-atlassian-id=\"557058:14b7fd50-d65a-47a8-825c-fa89681d07bd\">@Arthur Schang</span> , thanks I\u2019ve cloned your ignition branch and am trying to run the following:</p>\n<p>Terminal 1:</p>\n<div class=\"codehilite\"><pre><span></span>ign launch -v 4 virtual_stix.ign robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG_4\n</pre></div>\n\n\n<p>Terminal 2:</p>\n<div class=\"codehilite\"><pre><span></span>roslaunch helloworld_subt_launch helloworld-ign.launch\n</pre></div>\n\n\n<p>With errors and warnings of the following type:</p>\n<div class=\"codehilite\"><pre><span></span><span class=\"k\">[ WARN] [1562686798.884227893, 101.462000000]: W0709 11:39:58.000000 11804 tf_bridge.cc:52] Lookup would require extrapolation into the past.  Requested time 90.050000000 but the earliest data is at time 91.461000000, when looking up transform from frame [X1/base_link/imu_sensor] to frame [X1]</span>\n<span class=\"k\">[ WARN] [1562686798.884300216, 101.462000000]: W0709 11:39:58.000000 11804 tf_bridge.cc:52] Lookup would require extrapolation into the past.  Requested time 90.050000000 but the earliest data is at time 91.461000000, when looking up transform from frame [X1/base_link/imu_sensor] to frame [X1]</span>\n<span class=\"k\">[ERROR] [1562686799.471079435, 101.650000000]: Extrapolation Error looking up robot pose: Lookup would require extrapolation into the past.  Requested time 90.623000000 but the earliest data is at time 91.649000000, when looking up transform from frame [X1/base_link] to frame [map]</span>\n\n<span class=\"na\">[ WARN] [1562686799.512097470, 101.662000000]: W0709 11:39:59.000000 11804 tf_bridge.cc:52] Could not find a connection between &#39;X1&#39; and &#39;base_link&#39; because they are not part of the same tree.Tf has two or more unconnected trees.</span>\n<span class=\"na\">[ WARN] [1562686800.116323704, 101.863000000]: W0709 11:40:00.000000 11804 tf_bridge.cc:52] Could not find a connection between &#39;X1&#39; and &#39;base_link&#39; because they are not part of the same tree.Tf has two or more unconnected trees.</span>\n</pre></div>\n\n\n<p>Are these the same kinds of complaints you guys saw (as indicated by your commit message)?</p>\n<p>I\u2019m also getting these errors from the ignition terminal:</p>\n<div class=\"codehilite\"><pre><span></span>[ERROR] [1562686764.351808883]: Client [/X1/move_base] wants topic /X1/points to have datatype/md5sum [sensor_msgs/PointCloud/d8e9c3f5afbdd8a130fd1d2763945fca], but our version has [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181]. Dropping connection.\n[ERROR] [1562687005.015042569]: Client [/X1/move_base] wants topic /X1/points to have datatype/md5sum [sensor_msgs/PointCloud/d8e9c3f5afbdd8a130fd1d2763945fca], but our version has [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181]. Dropping connection.\n</pre></div>\n\n\n<p>I\u2019m also attaching my tf trees from view_frames. Notably, I have base_link-&gt;X1-&gt;X1/base_link. Is this expected behavior? Is this issue related at all to Issue <a data-is-external-link=\"true\" href=\"#!/osrf/subt/issues/100/accurate-uav-odometry-filtered-rostopic\" rel=\"nofollow\">#100</a>?</p>\n<p>Here is the roswtf output:</p>\n<div class=\"codehilite\"><pre><span></span>Loaded plugin tf.tfwtf\nLoaded plugin openni2_launch.wtf_plugin\nNo package or stack in context\n================================================================================\nStatic checks summary:\n\nNo errors or warnings\n================================================================================\nBeginning tests of your ROS graph. These may take awhile...\nanalyzing graph...\n... done analyzing graph\nrunning graph rules...\n... done running graph rules\nrunning tf checks, this will take a second...\n... tf checks complete\n\nOnline checks summary:\n\nFound 1 warning(s).\nWarnings are things that may be just fine, but are sometimes at fault\n\nWARNING The following node subscriptions are unconnected:\n * /rviz:\n   * /X1/projected_map_updates\n   * /X1/map_updates\n * /X1/move_base:\n   * /X1/move_base/cancel\n   * /X1/scan\n   * /X1/move_base_simple/goal\n\n\nFound 2 error(s).\n\nERROR The following nodes should be connected but aren&#39;t:\n * /X1/move_base-&gt;/X1/move_base (/X1/move_base/global_costmap/footprint)\n * /ignition-&gt;/X1/move_base (/X1/points)\n * /X1/move_base-&gt;/X1/move_base (/X1/move_base/local_costmap/footprint)\n\nERROR Different number of openni2 sensors found.\n * 0 openni2 sensors found (expected: 1).\n</pre></div>", "type": "rendered"}, "created_on": "2019-07-09T16:08:56.896263+00:00", "user": {"display_name": "Sarah Kitchen", "uuid": "{6e33efb0-dd9b-4c54-9597-53cb73099f33}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B6e33efb0-dd9b-4c54-9597-53cb73099f33%7D"}, "html": {"href": "https://bitbucket.org/%7B6e33efb0-dd9b-4c54-9597-53cb73099f33%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/29a4e0df12f5ebcc54cd596a60606526d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSK-1.png"}}, "nickname": "snkitche", "type": "user", "account_id": "5be108d7216ccf49622e6b67"}, "updated_on": "2019-07-09T16:31:47.817567+00:00", "type": "issue_comment", "id": 52912218}