{"links": {"self": {"href": "data/repositories/osrf/subt/pullrequests/353/comments/128475127.json"}, "html": {"href": "#!/osrf/subt/pull-requests/353/_/diff#comment-128475127"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 353, "links": {"self": {"href": "data/repositories/osrf/subt/pullrequests/353.json"}, "html": {"href": "#!/osrf/subt/pull-requests/353"}}, "title": "Model submission for X4 sensor config 2"}, "content": {"raw": "I made those changes to my local copy of submitted\\_models/ssci\\_x4\\_sensor\\_config\\_6, but when I tried to push, the remote branch appears to be gone now.  Is that because the PR has been accepted?  If so, I can\u2019t make these changes on this model, but I can on our other submissions that use this.  ", "markup": "markdown", "html": "<p>I made those changes to my local copy of submitted_models/ssci_x4_sensor_config_6, but when I tried to push, the remote branch appears to be gone now.  Is that because the PR has been accepted?  If so, I can\u2019t make these changes on this model, but I can on our other submissions that use this.  </p>", "type": "rendered"}, "created_on": "2019-12-11T23:20:43.098303+00:00", "user": {"display_name": "Neil Johnson", "uuid": "{ace5bb77-1f3f-47ce-ad95-ea205b690930}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bace5bb77-1f3f-47ce-ad95-ea205b690930%7D"}, "html": {"href": "https://bitbucket.org/%7Bace5bb77-1f3f-47ce-ad95-ea205b690930%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/7ff0dae55a4eb43a021cc9c08bbf30f5d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsNJ-3.png"}}, "nickname": "realdealneil1980", "type": "user", "account_id": "557058:21a4b3d0-2fa2-4202-9385-337ffcf40b2f"}, "updated_on": "2019-12-11T23:20:43.305035+00:00", "type": "pullrequest_comment", "id": 128475127}