{"links": {"self": {"href": "data/repositories/osrf/subt/issues/120/comments/53098769.json"}, "html": {"href": "#!/osrf/subt/issues/120#comment-53098769"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/120.json"}}, "type": "issue", "id": 120, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "Transform from X2_1/base_link/imu_sensor to X2_1/base_link is unavailable"}, "content": {"raw": "Thank you very much for your feedback.   \nFor me the TF tree looks not bad:\n\n![](data/bitbucket.org/repo/8ze6Mjd/images/152623770-tf-tree.png)\nThe problem occurs in the localization node. Here the complete first lines:\n\n\\[ WARN\\] \\[1563827173.117525065, 1066.787000000\\]: Detected jump back in time of 1.56383e\\+09s. Clearing TF buffer.  \n\\[ WARN\\] \\[1563827173.131819206, 1066.793000000\\]: Could not obtain transform from base\\_link to X2\\_1/base\\_link. Error was \"base\\_link\" passed to lookupTransform argument source\\_frame does not exist.  \n\\[ WARN\\] \\[1563827173.225551134, 1066.815000000\\]: Transform from X2\\_1/base\\_link/imu\\_sensor to X2\\_1/base\\_link was unavailable for the time requested. Using latest instead.  \n\u2026\n\nIn Gazebo 9 it worked but in Ignition it does not work any more. Research in the internet gives also statements that it could be a timing problem.", "markup": "markdown", "html": "<p>Thank you very much for your feedback. <br />\nFor me the TF tree looks not bad:</p>\n<p><img alt=\"\" src=\"data/bitbucket.org/repo/8ze6Mjd/images/152623770-tf-tree.png\" />\nThe problem occurs in the localization node. Here the complete first lines:</p>\n<p>[ WARN] [<a href=\"#!/osrf/subt/commits/1563827173\" rel=\"nofollow\" class=\"ap-connect-link\">1563827173</a>.<a href=\"#!/osrf/subt/commits/117525065\" rel=\"nofollow\" class=\"ap-connect-link\">117525065</a>, 1066.<a href=\"#!/osrf/subt/commits/787000000\" rel=\"nofollow\" class=\"ap-connect-link\">787000000</a>]: Detected jump back in time of 1.56383e+09s. Clearing TF buffer.<br />\n[ WARN] [<a href=\"#!/osrf/subt/commits/1563827173\" rel=\"nofollow\" class=\"ap-connect-link\">1563827173</a>.<a href=\"#!/osrf/subt/commits/131819206\" rel=\"nofollow\" class=\"ap-connect-link\">131819206</a>, 1066.<a href=\"#!/osrf/subt/commits/793000000\" rel=\"nofollow\" class=\"ap-connect-link\">793000000</a>]: Could not obtain transform from base_link to X2_1/base_link. Error was \"base_link\" passed to lookupTransform argument source_frame does not exist.<br />\n[ WARN] [<a href=\"#!/osrf/subt/commits/1563827173\" rel=\"nofollow\" class=\"ap-connect-link\">1563827173</a>.<a href=\"#!/osrf/subt/commits/225551134\" rel=\"nofollow\" class=\"ap-connect-link\">225551134</a>, 1066.<a href=\"#!/osrf/subt/commits/815000000\" rel=\"nofollow\" class=\"ap-connect-link\">815000000</a>]: Transform from X2_1/base_link/imu_sensor to X2_1/base_link was unavailable for the time requested. Using latest instead.<br />\n\u2026</p>\n<p>In Gazebo 9 it worked but in Ignition it does not work any more. Research in the internet gives also statements that it could be a timing problem.</p>", "type": "rendered"}, "created_on": "2019-07-22T20:57:10.221749+00:00", "user": {"display_name": "Sophisticated Engineering", "uuid": "{12ed2357-e253-4c67-a2b9-7e12c64773e4}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B12ed2357-e253-4c67-a2b9-7e12c64773e4%7D"}, "html": {"href": "https://bitbucket.org/%7B12ed2357-e253-4c67-a2b9-7e12c64773e4%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/2a19963da6b0f34b3be28d8690bdd711d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSE-6.png"}}, "nickname": "sopheng", "type": "user", "account_id": "5c0d82b3128c7106f57691a7"}, "updated_on": null, "type": "issue_comment", "id": 53098769}