{"links": {"self": {"href": "data/repositories/osrf/subt/issues/374/comments/56798610.json"}, "html": {"href": "#!/osrf/subt/issues/374#comment-56798610"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/subt/issues/374.json"}}, "type": "issue", "id": 374, "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "title": "cv_bridge exception"}, "content": {"raw": "I just noticed that Issue #353 and #363 were reporting the same exception and my robot `robotConfig1:=x3_sensor_config_4` also has RGBD camera. When I change robot configuration to different type camera, e.g. `robotConfig1:=x3_sensor_config_1`, the error disappears.", "markup": "markdown", "html": "<p>I just noticed that Issue <a href=\"#!/osrf/subt/issues/353/rgbd-camera-error-upon-launch\" rel=\"nofollow\" title=\"RGBD Camera error upon launch\" class=\"ap-connect-link\">#353</a> and <a href=\"#!/osrf/subt/issues/363/cv_bridge-exception-when-using-any-vehicle\" rel=\"nofollow\" title=\"cv_bridge exception when using any vehicle with depth camera (RGBD)\" class=\"ap-connect-link\"><s>#363</s></a> were reporting the same exception and my robot <code>robotConfig1:=x3_sensor_config_4</code> also has RGBD camera. When I change robot configuration to different type camera, e.g. <code>robotConfig1:=x3_sensor_config_1</code>, the error disappears.</p>", "type": "rendered"}, "created_on": "2020-04-05T08:42:54.781703+00:00", "user": {"display_name": "Paul Jurczak", "uuid": "{d17ee528-259a-4ff4-b5b0-007442ea3edb}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd17ee528-259a-4ff4-b5b0-007442ea3edb%7D"}, "html": {"href": "https://bitbucket.org/%7Bd17ee528-259a-4ff4-b5b0-007442ea3edb%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/11246ef0203dec00e61a34f4d35987e7d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsPJ-3.png"}}, "nickname": "pauljurczak", "type": "user", "account_id": "557058:13c5913f-35b3-41ba-8f6d-5887d9158e52"}, "updated_on": null, "type": "issue_comment", "id": 56798610}