{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "links": {"attachments": {"href": "data/repositories/osrf/subt/issues/131/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/subt/issues/131.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/subt/issues/131/watch"}, "comments": {"href": "data/repositories/osrf/subt/issues/131/comments_page=1.json"}, "html": {"href": "#!/osrf/subt/issues/131/missing-logs-on-ignition-submission-portal"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/subt/issues/131/vote"}}, "reporter": {"display_name": "Arthur Schang", "uuid": "{1403972a-9b64-442b-a69c-d7e9557e1d87}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B1403972a-9b64-442b-a69c-d7e9557e1d87%7D"}, "html": {"href": "https://bitbucket.org/%7B1403972a-9b64-442b-a69c-d7e9557e1d87%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/initials/AS-0.png"}}, "nickname": "Arthur Schang", "type": "user", "account_id": "557058:14b7fd50-d65a-47a8-825c-fa89681d07bd"}, "title": "Missing Logs on Ignition Submission Portal", "component": null, "votes": 0, "watches": 1, "content": {"raw": "I have previously submitted to virtual STIX and tunnel practice 1 & 2 on cloudsim and gotten logs back \\(even whenever initialization failed\\).  I successfully ran a submission on tunnel practice 2 and then made slight modifications \\(nothing that should break anything\\) and resubmitted to virtual stix on cloudsim.  I received \u201cTerminated With no errors\u201d for both runs yet I only got logs for tunnel practice 2 and none for virtual stix.  I don\u2019t think this is an issue with the virtual stix as I have gotten logs back from a previous run on virtual stix.\r\n\r\n\u200c\r\n\r\nThe message I receive whenever I click to download logs is \u201cThere are no logs to download\u201d", "markup": "markdown", "html": "<p>I have previously submitted to virtual STIX and tunnel practice 1 &amp; 2 on cloudsim and gotten logs back (even whenever initialization failed).  I successfully ran a submission on tunnel practice 2 and then made slight modifications (nothing that should break anything) and resubmitted to virtual stix on cloudsim.  I received \u201cTerminated With no errors\u201d for both runs yet I only got logs for tunnel practice 2 and none for virtual stix.  I don\u2019t think this is an issue with the virtual stix as I have gotten logs back from a previous run on virtual stix.</p>\n<p>\u200c</p>\n<p>The message I receive whenever I click to download logs is \u201cThere are no logs to download\u201d</p>", "type": "rendered"}, "assignee": {"display_name": "Alfredo Bencomo", "uuid": "{84891a71-dff2-4b97-8891-9446c16e6f89}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B84891a71-dff2-4b97-8891-9446c16e6f89%7D"}, "html": {"href": "https://bitbucket.org/%7B84891a71-dff2-4b97-8891-9446c16e6f89%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/5cf75629ff02b50ea27b2817/82be1d48-d490-4d7b-8ddb-a8093b9417a6/128"}}, "nickname": "bencomo", "type": "user", "account_id": "5cf75629ff02b50ea27b2817"}, "state": "closed", "version": null, "edited_on": null, "created_on": "2019-07-25T13:34:45.253450+00:00", "milestone": null, "updated_on": "2019-10-31T05:58:13.629494+00:00", "type": "issue", "id": 131}