{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "links": {"attachments": {"href": "data/repositories/osrf/subt/issues/187/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/subt/issues/187.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/subt/issues/187/watch"}, "comments": {"href": "data/repositories/osrf/subt/issues/187/comments_page=1.json"}, "html": {"href": "#!/osrf/subt/issues/187/simulation-not-working-after-update"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/subt/issues/187/vote"}}, "reporter": {"display_name": "Chris Fotache", "uuid": "{cd3b9ed2-9a40-452b-ab2c-331d13096957}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd3b9ed2-9a40-452b-ab2c-331d13096957%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd3b9ed2-9a40-452b-ab2c-331d13096957%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/40ac88759cdee5d3abe8a21f3374c697d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsCF-1.png"}}, "nickname": "chrisfotache", "type": "user", "account_id": "5c93ca4876fb272e06b54f6c"}, "title": "Simulation not working after update", "component": null, "votes": 0, "watches": 5, "content": {"raw": "I just did an apt update & upgrade, and now the simulation doesn\u2019t work properly anymore. IGN starts and shows the tunnel and robots, but there are no topics available, so our program can\u2019t send commands anymore.\r\n\r\nI see these errors when I launch it:\r\n\r\nERROR: cannot launch node of type \\[ros1\\_ign\\_bridge/parameter\\_bridge\\]: ros1\\_ign\\_bridge  \r\nROS path \\[0\\]=/opt/ros/melodic/share/ros  \r\nROS path \\[1\\]=/home/cfotache/subt\\_ws/install/share  \r\nROS path \\[2\\]=/opt/ros/melodic/share  \r\nERROR: cannot launch node of type \\[ros1\\_ign\\_image/image\\_bridge\\]: ros1\\_ign\\_image  \r\nROS path \\[0\\]=/opt/ros/melodic/share/ros  \r\nROS path \\[1\\]=/home/cfotache/subt\\_ws/install/share  \r\nROS path \\[2\\]=/opt/ros/melodic/share\r\n\r\n\\(they get repeated several times\\).\r\n\r\nRunning this in a catkin workspace\u2026 Did the hg pull and catkin\\_make install.", "markup": "markdown", "html": "<p>I just did an apt update &amp; upgrade, and now the simulation doesn\u2019t work properly anymore. IGN starts and shows the tunnel and robots, but there are no topics available, so our program can\u2019t send commands anymore.</p>\n<p>I see these errors when I launch it:</p>\n<p>ERROR: cannot launch node of type [ros1_ign_bridge/parameter_bridge]: ros1_ign_bridge<br />\nROS path [0]=/opt/ros/melodic/share/ros<br />\nROS path [1]=/home/cfotache/subt_ws/install/share<br />\nROS path [2]=/opt/ros/melodic/share<br />\nERROR: cannot launch node of type [ros1_ign_image/image_bridge]: ros1_ign_image<br />\nROS path [0]=/opt/ros/melodic/share/ros<br />\nROS path [1]=/home/cfotache/subt_ws/install/share<br />\nROS path [2]=/opt/ros/melodic/share</p>\n<p>(they get repeated several times).</p>\n<p>Running this in a catkin workspace\u2026 Did the hg pull and catkin_make install.</p>", "type": "rendered"}, "assignee": {"display_name": "Alfredo Bencomo", "uuid": "{84891a71-dff2-4b97-8891-9446c16e6f89}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B84891a71-dff2-4b97-8891-9446c16e6f89%7D"}, "html": {"href": "https://bitbucket.org/%7B84891a71-dff2-4b97-8891-9446c16e6f89%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/5cf75629ff02b50ea27b2817/82be1d48-d490-4d7b-8ddb-a8093b9417a6/128"}}, "nickname": "bencomo", "type": "user", "account_id": "5cf75629ff02b50ea27b2817"}, "state": "closed", "version": null, "edited_on": null, "created_on": "2019-09-17T20:23:58.953666+00:00", "milestone": null, "updated_on": "2019-10-31T05:53:18.422063+00:00", "type": "issue", "id": 187}