{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/subt.json"}, "html": {"href": "#!/osrf/subt"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3c95f6ad-c304-407c-b838-09597d836552}ts=2272898"}}, "type": "repository", "name": "subt", "full_name": "osrf/subt", "uuid": "{3c95f6ad-c304-407c-b838-09597d836552}"}, "links": {"attachments": {"href": "data/repositories/osrf/subt/issues/350/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/subt/issues/350.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/subt/issues/350/watch"}, "comments": {"href": "data/repositories/osrf/subt/issues/350/comments_page=1.json"}, "html": {"href": "#!/osrf/subt/issues/350/error-5514-circuit-rule-not-found"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/subt/issues/350/vote"}}, "reporter": {"display_name": "GoRobotGo", "uuid": "{2fd8dac8-286d-461a-b7dd-dba99deea025}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2fd8dac8-286d-461a-b7dd-dba99deea025%7D"}, "html": {"href": "https://bitbucket.org/%7B2fd8dac8-286d-461a-b7dd-dba99deea025%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/6431739b101c18640b5a84d359fdd274d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsG-4.png"}}, "nickname": "GoRobotGo", "type": "user", "account_id": "557058:44b40072-c04b-41ae-ad09-376db9ebffa1"}, "title": "Error #5514: Circuit rule not found.", "component": null, "votes": 1, "watches": 4, "content": {"raw": "I just tried a cloudsim run against Urban Circuit World 1 and received the error message in the title.", "markup": "markdown", "html": "<p>I just tried a cloudsim run against Urban Circuit World 1 and received the error message in the title.</p>", "type": "rendered"}, "assignee": null, "state": "resolved", "version": null, "edited_on": null, "created_on": "2020-03-03T20:49:35.164012+00:00", "milestone": null, "updated_on": "2020-03-09T13:24:27.030245+00:00", "type": "issue", "id": 350}